Issue #135: SuppressionPatchXpathFilter: PackageAnnotation's context strategy
checkstyle/patch-filters pull request #319
Opened 2020-08-26 15:08 UTC by HuGanghui

Issue #135: SuppressionPatchXpathFilter: PackageAnnotation's context strategy

2020-08-26 21:18 UTC, rdiachenko requested changes

2020-08-26 21:18 UTC, rdiachenko commented on src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/patchedline/defaultContextConfig.xml
> +            <property name="strategy" value="newline" />
should be `patchedline`

2020-08-27 02:19 UTC, HuGanghui commented on src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/PackageAnnotation/patchedline/defaultContextConfig.xml
> +            <property name="strategy" value="newline" />
done

2020-08-27 20:39 UTC, rdiachenko approved these changes
LGTM

2020-08-27 20:39 UTC, merged