Issue #302: add RightCurly and AvoidNestedBlocks's new suppressed violations
checkstyle/patch-filters pull request #320
Opened 2020-08-27 14:23 UTC by HuGanghui

Issue #302: add RightCurly and AvoidNestedBlocks's new suppressed violations

2020-08-27 16:39 UTC, baratali requested changes

2020-08-27 16:39 UTC, baratali commented on src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/AvoidNestedBlocks/context/Test.java
> +        {
please add `// violation without filter`

2020-08-27 16:39 UTC, baratali commented on src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/RightCurly/context/Test.java
> +        }
please add `// violation without filter`

2020-08-28 01:51 UTC, HuGanghui commented on src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/AvoidNestedBlocks/context/Test.java
> +        {
done

2020-08-28 01:51 UTC, HuGanghui commented on src/test/resources/com/puppycrawl/tools/checkstyle/filters/suppressionjavapatchfilter/RightCurly/context/Test.java
> +        }
done

2020-08-28 08:27 UTC, baratali approved these changes

2020-08-28 08:27 UTC, merged