Issue #332: Update README.md to add checkNamesForContextStrategyByTokenOrAncestorSet property
checkstyle/patch-filters pull request #333
Opened 2020-08-29 07:48 UTC by HuGanghui

Issue #332: Update README.md to add checkNamesForContextStrategyByTokenOrAncestorSet property

2020-09-01 19:44 UTC, rdiachenko commented
@HuGanghui please rebase

2020-09-02 13:53 UTC, HuGanghui commented
rebased.

2020-09-02 19:17 UTC, rdiachenko requested changes

2020-09-03 03:15 UTC, HuGanghui commented on README.md
> + | checkNamesForContextStrategyByTokenOrAncestorSet | String has user defined TreeWalker Checks that need modify violation nodes to their ancestor node to expand the context scope, split by comma | [
ok, done

2020-09-03 19:37 UTC, rdiachenko approved these changes
LGTM

2020-09-03 19:37 UTC, merged